In [85]:
import pandas as pd
import numpy as np
import random

import sklearn
from sklearn import linear_model as lm
sklearn.__version__

'0.22.2.post1'

In [86]:
def compare(beta1, beta2):
    print('''
Our solver:
{}
Scikit-learn:
{}

Difference between the two:
{}
        '''.format(beta1, beta2, np.sum((beta1-beta2)**2))
    )

In [87]:
X_test_mat100 = pd.read_csv('../data/Xte_mat100.csv',sep=' ',header=None).values
X_train_mat100 = pd.read_csv('../data/Xtr_mat100.csv',sep=' ',header=None).values


X_test = pd.read_csv('../data/Xte.csv',sep=',',index_col=0).values
X_train = pd.read_csv('../data/Xtr.csv',sep=',',index_col=0).values

y_train = pd.read_csv('../data/Ytr.csv',sep=',',index_col=0).values

In [88]:
print('x_train: {} y_train {}'.format(X_train_mat100.shape,y_train.shape))
print('x_train: {} y_train {}'.format(X_train.shape,y_train.shape))
print('x_test: {}'.format(X_test.shape))

x_train: (2000, 100) y_train (2000, 1)
x_train: (2000, 1) y_train (2000, 1)
x_test: (1000, 1)


In [89]:
y_train[:10]

array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1]])

In [90]:
X_train_mat100[:10,:10]

array([[0.01086957, 0.01086957, 0.01086957, 0.0326087 , 0.01086957,
        0.0326087 , 0.01086957, 0.        , 0.        , 0.01086957],
       [0.        , 0.01086957, 0.02173913, 0.        , 0.02173913,
        0.02173913, 0.        , 0.01086957, 0.02173913, 0.01086957],
       [0.02173913, 0.        , 0.        , 0.        , 0.04347826,
        0.01086957, 0.01086957, 0.01086957, 0.        , 0.02173913],
       [0.        , 0.02173913, 0.0326087 , 0.        , 0.02173913,
        0.        , 0.0326087 , 0.01086957, 0.02173913, 0.        ],
       [0.01086957, 0.04347826, 0.        , 0.0326087 , 0.01086957,
        0.01086957, 0.        , 0.01086957, 0.01086957, 0.        ],
       [0.05434783, 0.02173913, 0.        , 0.        , 0.        ,
        0.02173913, 0.        , 0.01086957, 0.        , 0.01086957],
       [0.        , 0.        , 0.02173913, 0.        , 0.0326087 ,
        0.        , 0.02173913, 0.01086957, 0.        , 0.        ],
       [0.01086957, 0.01086957, 0.0108695

In [91]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import scale


X_train_mat100 = scale(X_train_mat100)

X_train, X_test, y_train, y_test = train_test_split(
    X_train_mat100, y_train, test_size=0.33, random_state=42)

print(X_train.shape,X_test.shape,y_train.shape, y_test.shape)

(1340, 100) (660, 100) (1340, 1) (660, 1)


In [60]:
# Ridge Regression (RR)
def solveRR(y, X, lam):
    n, p = X.shape
    assert (len(y) == n)
    
    A = X.T.dot(X)
    # Adjust diagonal due to Ridge
    A[np.diag_indices_from(A)] += lam * n
    b = X.T.dot(y)
    
    # Hint:
    beta = np.linalg.solve(A, b)
    # Finds solution to the linear system Ax = b
    return (beta)

# Weighted Ridge Regression (WRR)
def solveWRR(y, X, w, lam):
    n, p = X.shape
    assert (len(y) == len(w) == n)
    
    y1 = np.sqrt(w) * y
    X1 = (np.sqrt(w) * X.T).T
    # Hint:
    # Find y1 and X1 such that:
    beta = solveRR(y1, X1, lam)
    return (beta)

In [94]:
# lam = 0.1
# w = np.random.rand(len(y_train))

# # Our solver
# beta1 = solveWRR(y_train, X_train, w, lam)

# # Python solver
# alpha = lam * X_train.shape[0]
model = lm.Ridge(alpha=alpha, fit_intercept=False, normalize=False)
beta2 = model.fit(X_train,y_train)

# Check
# compare(beta1, beta2)
# beta1.shape
# accuracy_score(y_test, )
model.predict(X_test)

array([[-2.72439237e-01],
       [-2.33414033e-01],
       [ 2.91346840e-01],
       [-1.61614633e-01],
       [ 2.00281986e-01],
       [-1.33548200e-01],
       [-2.15761754e-02],
       [ 1.72568401e-01],
       [-9.43417063e-02],
       [-2.64957974e-01],
       [-5.01751733e-02],
       [ 1.11747247e-01],
       [-1.16937517e-01],
       [-3.14391523e-01],
       [ 3.47650063e-01],
       [-2.09353682e-02],
       [-2.77515115e-02],
       [ 1.56597597e-01],
       [-8.11856509e-02],
       [ 6.31477186e-02],
       [-1.37817534e-01],
       [-1.36408913e-01],
       [-2.75079365e-02],
       [-3.49338799e-01],
       [ 3.15619129e-01],
       [ 2.16929143e-02],
       [-1.59997792e-01],
       [-1.41785210e-01],
       [ 2.32079601e-01],
       [ 2.22511920e-02],
       [ 8.02405807e-02],
       [ 1.95621112e-01],
       [ 1.43810174e-01],
       [ 5.78204451e-02],
       [-3.48101438e-01],
       [ 1.29749230e-01],
       [-5.94748544e-02],
       [ 1.41404589e-01],
       [ 3.8

In [64]:

# Compute predicted probabilities and classes
probas_pred = 1 / (1+np.exp(-beta.T.dot(X_test.T)))
y_pred = np.sign(probas_pred-.5)

In [65]:
from sklearn.metrics import accuracy_score, roc_auc_score

print("Our model's performance:")
print('Accuracy: {:.2%}'.format(accuracy_score(y_test, y_pred.T)))
# print('AUC: {:.2%}'.format(roc_auc_score(y_test, probas_pred)))

Our model's performance:


ValueError: Classification metrics can't handle a mix of binary and multilabel-indicator targets

In [67]:
y_test.shape,y_pred.shape

((660, 1), (1340, 660))